<?php

return [
    'APP_ADMIN_EMAIL' => null,
    'APP_ADMIN_MAILER_LOGIN' => null,
    'APP_ADMIN_MAILER_PASS' => null,
    'APP_DB_DOP_QUERY_PARAMS' => null,
    'APP_DB_HOST_IP' => null,
    'APP_DB_NAME' => null,
    'APP_DB_PASS' => null,
    'APP_DB_USER' => null,
    'APP_GITHUB_API_AUTH_TOKEN' => null,
    'APP_GITHUB_API_REPO' => null,
    'APP_GITHUB_API_REPO_OWNER' => null,
    'APP_MAILER_MAILGUN_TRANSPORT_API_KEY' => null,
    'APP_MAILER_MAILGUN_TRANSPORT_DOMAIN' => null,
    'APP_OPEN_CAGE_API_KEY' => null,
    'APP_TELEGRAM_BOT_API_TOKEN' => null,
    'APP_TELEGRAM_BOT_NAME' => null,
    'APP_TELEGRAM_TOKEN' => null,
    'APP_TELEGRAM_Y_KASSA_API_TOKEN' => null,
    'APP_TEST_EMAIL' => null,
    'APP_TEST_TELEGRAM_BOT_API_TOKEN' => null,
    'APP_TEST_TELEGRAM_BOT_CHAT_ID' => null,
    'APP_TEST_TELEGRAM_CHAT_ID' => null,
    'APP_TEST_TELEGRAM_TOKEN' => null,
    'APP_TEST_TELEGRAM_Y_KASSA_API_TOKEN' => null,
    'APP_Y_KASSA_API_TOKEN' => null,
    'JWT_PASSPHRASE' => null,
    'MERCURE_JWT_SECRET' => null,
];
