framework:
    trusted_hosts: ~
    trusted_proxies: '127.0.0.1,PRIVATE_SUBNETS'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]

    http_cache:
        enabled: true
