lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 20

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        query_parameter:
            enabled: true
            name: token

    remove_token_from_body_when_cookies_used: false

    blocklist_token:
        enabled: true
        cache: 'cache.app'

#    encoder:
#        service: lexik_jwt_authentication.encoder.web_token
