controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#user_context_hash:
#    path: /_fos_user_context_hash

api_token_invalidate:
    path: /api/token/invalidate
